# Nombre del proyecto
spring.application.name=is2.grupo3

# Servidor de la aplicación web
server.port=${PORT:8080}

# CONEXIÓN DIRECTA - Reemplaza los datos de abajo por tus datos reales de Postgres:
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=LQYQzAptwVgyHSYDoLaWwGzukADlHLEO
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Thymeleaf para desarrollo
spring.thymeleaf.cache=false
