# Nombre del proyecto
spring.application.name=is2.grupo3

# Servidor de la aplicación web (Tomcat leerá el puerto interno de Railway)
server.port=${PORT:8080}

# Configuración de la conexión a PostgreSQL con variables nativas de Railway y SSL forzado
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evita que Spring aborte el inicio si la base de datos tarda unos milisegundos en responder
spring.datasource.hikari.initialization-fail-timeout=0

# Configuración de Thymeleaf para desarrollo
spring.thymeleaf.cache=false
